#!/bin/bash -x

CONSUL_VERSION="0.4.1"
CONSUL_TARBALL_DIR=blobs/consul
CONSUL_TARBALL_FILE=$CONSUL_TARBALL_DIR/consul-${CONSUL_VERSION}_linux_amd64.zip

if [ ! -f $CONSUL_TARBALL_FILE ]; then
  mkdir -p $CONSUL_TARBALL_DIR
  echo "Downloading consul version $CONSUL_VERSION tarball"
  wget https://dl.bintray.com/mitchellh/consul/${CONSUL_VERSION}_linux_amd64.zip -O $CONSUL_TARBALL_FILE
else
  echo "Detected consul tarball. Not downloading."
fi
