meta:
  environment: (( param "please set meta environment" ))
  dns_root: (( param "please set meta dns_root" ))
  security_groups: (( param "please set meta security_groups" ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: consul
    networks:
      - name: consul1
    persistent_disk: (( grab meta.persistent_disk ))
    properties:
      consul:
        join_host: (( concat "0.consul-z1.consul1." meta.environment "." meta.dns_root ))

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: consul1
    type: dynamic
    cloud_properties:
      security_groups: (( grab meta.security_groups ))
